@url = http://localhost:3000/api/v1

GET {{url}}/blogs

###


GET {{url}}/blogs/1

###

POST {{url}}/blogs
Content-Type: application/json

{
  "title": "Nest-JS",
  "body": "This is a blog post of Nest JS"
}

###

PUT {{url}}/blogs/1590691185712
Content-Type: application/json

{
  "title": "Updated title!"
}

###

DELETE {{url}}/blogs/1590691185712

###
GET {{url}}/comments

###

GET {{url}}/comments/1

###

POST {{url}}/comments
Content-Type: application/json

{
  "text": "Just one another comment"
}

###

DELETE {{url}}/comments/

